-- ============================================================
-- EF Core Migration: InitPostgres
-- Generated for Supabase PostgreSQL
-- Run this in Supabase SQL Editor
-- ============================================================

-- EF Migrations history table (required by EF Core)
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "id" text NOT NULL,
    "user_name" character varying(256),
    "normalized_user_name" character varying(256),
    "email" character varying(256),
    "normalized_email" character varying(256),
    "email_confirmed" boolean NOT NULL,
    "password_hash" text,
    "security_stamp" text,
    "concurrency_stamp" text,
    "phone_number" character varying(50),
    "full_name" character varying(100),
    "first_name" character varying(50),
    "last_name" character varying(50),
    "bio" character varying(500),
    "avatar_url" character varying(500),
    "is_available" boolean NOT NULL,
    "follower_count" integer NOT NULL DEFAULT 0,
    "following_count" integer NOT NULL DEFAULT 0,
    "post_count" integer NOT NULL,
    "is_locked" boolean NOT NULL,
    "locked_at" timestamp with time zone,
    "unlock_date" timestamp with time zone,
    "lock_reason" character varying(500),
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("id") ON DELETE CASCADE
);

CREATE TABLE "follows" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "follower_id" character varying(450) NOT NULL,
    "following_id" character varying(450) NOT NULL,
    CONSTRAINT "PK_follows" PRIMARY KEY ("id"),
    CONSTRAINT "FK_follows_AspNetUsers_follower_id" FOREIGN KEY ("follower_id")
        REFERENCES "AspNetUsers" ("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_follows_AspNetUsers_following_id" FOREIGN KEY ("following_id")
        REFERENCES "AspNetUsers" ("id") ON DELETE RESTRICT
);

CREATE TABLE "nutrition_profile" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Gender" character varying(10) NOT NULL,
    "Age" integer NOT NULL,
    "Height" numeric NOT NULL,
    "Weight" numeric NOT NULL,
    "BMI" numeric NOT NULL,
    "BMIStatus" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_nutrition_profile" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_nutrition_profile_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("id") ON DELETE CASCADE
);

CREATE TABLE "posts" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "content" text NOT NULL,
    "image_url" character varying(500),
    "created_at" timestamp with time zone NOT NULL,
    "like_count" integer NOT NULL DEFAULT 0,
    "comment_count" integer NOT NULL DEFAULT 0,
    "user_id" character varying(450) NOT NULL,
    CONSTRAINT "PK_posts" PRIMARY KEY ("id"),
    CONSTRAINT "FK_posts_AspNetUsers_user_id" FOREIGN KEY ("user_id")
        REFERENCES "AspNetUsers" ("id") ON DELETE RESTRICT
);

CREATE TABLE "reported_contents" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "content_type" character varying(50) NOT NULL,
    "content_id" character varying(450) NOT NULL,
    "reason" character varying(100) NOT NULL,
    "description" character varying(1000),
    "status" character varying(20) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "resolved_at" timestamp with time zone,
    "admin_note" character varying(1000),
    "reporter_id" character varying(450),
    "resolved_by_id" character varying(450),
    "reporter_fullname" character varying(255),
    "target_user_id" character varying(450),
    "target_user_fullname" character varying(255),
    "target_content_snapshot" character varying(2000),
    CONSTRAINT "PK_reported_contents" PRIMARY KEY ("id"),
    CONSTRAINT "FK_reported_contents_AspNetUsers_reporter_id" FOREIGN KEY ("reporter_id")
        REFERENCES "AspNetUsers" ("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_reported_contents_AspNetUsers_resolved_by_id" FOREIGN KEY ("resolved_by_id")
        REFERENCES "AspNetUsers" ("id") ON DELETE RESTRICT
);

CREATE TABLE "nutrition_chat_session" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NutritionProfileId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_nutrition_chat_session" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_nutrition_chat_session_nutrition_profile_NutritionProfileId"
        FOREIGN KEY ("NutritionProfileId")
        REFERENCES "nutrition_profile" ("Id") ON DELETE CASCADE
);

CREATE TABLE "comments" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "content" character varying(2000) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "like_count" integer NOT NULL DEFAULT 0,
    "post_id" integer NOT NULL,
    "user_id" character varying(450) NOT NULL,
    CONSTRAINT "PK_comments" PRIMARY KEY ("id"),
    CONSTRAINT "FK_comments_AspNetUsers_user_id" FOREIGN KEY ("user_id")
        REFERENCES "AspNetUsers" ("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_comments_posts_post_id" FOREIGN KEY ("post_id")
        REFERENCES "posts" ("id") ON DELETE RESTRICT
);

CREATE TABLE "like_posts" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" character varying(450) NOT NULL,
    "post_id" integer NOT NULL,
    CONSTRAINT "PK_like_posts" PRIMARY KEY ("id"),
    CONSTRAINT "FK_like_posts_AspNetUsers_user_id" FOREIGN KEY ("user_id")
        REFERENCES "AspNetUsers" ("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_like_posts_posts_post_id" FOREIGN KEY ("post_id")
        REFERENCES "posts" ("id") ON DELETE RESTRICT
);

CREATE TABLE "saved_posts" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" character varying(450) NOT NULL,
    "post_id" integer NOT NULL,
    CONSTRAINT "PK_saved_posts" PRIMARY KEY ("id"),
    CONSTRAINT "FK_saved_posts_AspNetUsers_user_id" FOREIGN KEY ("user_id")
        REFERENCES "AspNetUsers" ("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_saved_posts_posts_post_id" FOREIGN KEY ("post_id")
        REFERENCES "posts" ("id") ON DELETE RESTRICT
);

CREATE TABLE "nutrition_chat_message" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SessionId" integer NOT NULL,
    "Role" character varying(20) NOT NULL,
    "Content" text NOT NULL,
    "ParsedMealsJson" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_nutrition_chat_message" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_nutrition_chat_message_nutrition_chat_session_SessionId"
        FOREIGN KEY ("SessionId")
        REFERENCES "nutrition_chat_session" ("Id") ON DELETE CASCADE
);

CREATE TABLE "like_comments" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" character varying(450) NOT NULL,
    "comment_id" integer NOT NULL,
    CONSTRAINT "PK_like_comments" PRIMARY KEY ("id"),
    CONSTRAINT "FK_like_comments_AspNetUsers_user_id" FOREIGN KEY ("user_id")
        REFERENCES "AspNetUsers" ("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_like_comments_comments_comment_id" FOREIGN KEY ("comment_id")
        REFERENCES "comments" ("id") ON DELETE RESTRICT
);

CREATE TABLE "notifications" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "type" integer NOT NULL,
    "content" character varying(500) NOT NULL,
    "is_read" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" character varying(450) NOT NULL,
    "actor_id" character varying(450),
    "post_id" integer,
    "comment_id" integer,
    CONSTRAINT "PK_notifications" PRIMARY KEY ("id"),
    CONSTRAINT "FK_notifications_AspNetUsers_actor_id" FOREIGN KEY ("actor_id")
        REFERENCES "AspNetUsers" ("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_notifications_AspNetUsers_user_id" FOREIGN KEY ("user_id")
        REFERENCES "AspNetUsers" ("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_notifications_comments_comment_id" FOREIGN KEY ("comment_id")
        REFERENCES "comments" ("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_notifications_posts_post_id" FOREIGN KEY ("post_id")
        REFERENCES "posts" ("id") ON DELETE RESTRICT
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE INDEX "EmailIndex" ON "AspNetUsers" ("normalized_email");
CREATE UNIQUE INDEX "IX_AspNetUsers_email" ON "AspNetUsers" ("email");
CREATE UNIQUE INDEX "IX_AspNetUsers_user_name" ON "AspNetUsers" ("user_name");
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("normalized_user_name");
CREATE INDEX "IX_comments_post_id" ON "comments" ("post_id");
CREATE INDEX "IX_comments_user_id" ON "comments" ("user_id");
CREATE UNIQUE INDEX "IX_follows_follower_id_following_id" ON "follows" ("follower_id", "following_id");
CREATE INDEX "IX_follows_following_id" ON "follows" ("following_id");
CREATE INDEX "IX_like_comments_comment_id" ON "like_comments" ("comment_id");
CREATE INDEX "IX_like_comments_created_at" ON "like_comments" ("created_at");
CREATE INDEX "IX_like_comments_user_id" ON "like_comments" ("user_id");
CREATE UNIQUE INDEX "IX_like_comments_user_id_comment_id" ON "like_comments" ("user_id", "comment_id");
CREATE INDEX "IX_like_posts_created_at" ON "like_posts" ("created_at");
CREATE INDEX "IX_like_posts_post_id" ON "like_posts" ("post_id");
CREATE INDEX "IX_like_posts_user_id" ON "like_posts" ("user_id");
CREATE UNIQUE INDEX "IX_like_posts_user_id_post_id" ON "like_posts" ("user_id", "post_id");
CREATE INDEX "IX_notifications_actor_id" ON "notifications" ("actor_id");
CREATE INDEX "IX_notifications_comment_id" ON "notifications" ("comment_id");
CREATE INDEX "IX_notifications_is_read" ON "notifications" ("is_read");
CREATE INDEX "IX_notifications_post_id" ON "notifications" ("post_id");
CREATE INDEX "IX_notifications_user_id" ON "notifications" ("user_id");
CREATE INDEX "IX_notifications_user_id_is_read" ON "notifications" ("user_id", "is_read");
CREATE INDEX "IX_nutrition_chat_message_CreatedAt" ON "nutrition_chat_message" ("CreatedAt");
CREATE INDEX "IX_nutrition_chat_message_SessionId" ON "nutrition_chat_message" ("SessionId");
CREATE INDEX "IX_nutrition_chat_session_CreatedAt" ON "nutrition_chat_session" ("CreatedAt");
CREATE UNIQUE INDEX "IX_nutrition_chat_session_NutritionProfileId" ON "nutrition_chat_session" ("NutritionProfileId");
CREATE UNIQUE INDEX "IX_nutrition_profile_UserId" ON "nutrition_profile" ("UserId");
CREATE INDEX "IX_posts_created_at" ON "posts" ("created_at");
CREATE INDEX "IX_posts_user_id" ON "posts" ("user_id");
CREATE INDEX "IX_reported_contents_content_type_content_id" ON "reported_contents" ("content_type", "content_id");
CREATE INDEX "IX_reported_contents_reporter_id" ON "reported_contents" ("reporter_id");
CREATE INDEX "IX_reported_contents_resolved_by_id" ON "reported_contents" ("resolved_by_id");
CREATE INDEX "IX_reported_contents_status" ON "reported_contents" ("status");
CREATE INDEX "IX_saved_posts_created_at" ON "saved_posts" ("created_at");
CREATE INDEX "IX_saved_posts_post_id" ON "saved_posts" ("post_id");
CREATE INDEX "IX_saved_posts_user_id" ON "saved_posts" ("user_id");
CREATE UNIQUE INDEX "IX_saved_posts_user_id_post_id" ON "saved_posts" ("user_id", "post_id");

-- ============================================================
-- MARK MIGRATION AS APPLIED (required for EF Core)
-- ============================================================
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260330212356_InitPostgres', '8.0.11');
